# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 730a58b2a21c2ff1f44eebb27b95a385e27e4481597c9b52fc2095fe4e1c041c6a002b90a1e76250ab88c231905881fefefd61891f7778620ffa3aedaba820eb

test:
  secret_key_base: 8df84245555c6a06969c4d50a7feb1dd084341d9187f1667004a520c7796da99c95784f19582667c6a7d2c813c5f55c84ffb2cbf10335dded317992f15a08777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
